spring.application.name=Springboot-API-REST
server.port=8081
spring.web.allow-cors=true

#Configuracion de la base de datos MySQL
#Las propiedades de datasource (url, username, password) se proporcionan
#como variables de entorno en el despliegue de Kubernetes.
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.platform=mysql

#Configuracion de Hibernate
spring.jpa.database=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

springdoc.swagger-ui.path=/swagger-ui.html